const initialCategories = [
  { name: "Marvel", 
    description: "Categoría Marvel", 
  },
  { name: "DC Comics", 
    description: "Categoría DC Comics", 
  },
  { name: "Avengers", 
    description: "Categoría Avengers", 
  },
  { name: "X-Men", 
    description: "Categoría X-Men", 
  },
  { name: "Fantastic Four", 
    description: "Categoría Fantastic Four", 
  },
  { name: "Justice League", 
    description: "Categoría Justice League", 
  },
  { name: "Legend", 
    description: "Categoría Legend", 
  },
  { name: "Young Titans", 
    description: "Categoría Young Titans", 
  },
];
const initialProducts = [
  {
    name: "Capitán América",
    description: "Este es el funko del Capi",
    price: 100,
    imagen: "https://lafrikileria.com/14056-large_default/funko-pop-capitan-america-avengers.jpg",
    stock: "true",
  },
  {
    name: "Capitana Marvel",
    description: "Este es el funko de la Carol Danvers",
    price: 100,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQtymm2PJTJ9HaNGaXrAl7u2vsWF3duGY7yFw&usqp=CAU",
    stock: "true",
  },
  {
    name: "Iron Man",
    description: "Este es el funko de I am Iron Man, alias Tony Stark",
    price: 100,
    imagen: "https://http2.mlstatic.com/funko-pop-marvel-avengers-infinity-war-iron-man-figura-de-vi-D_NQ_NP_723986-MCO31542984644_072019-F.jpg",
    stock: "true",
  },
  {
    name: "EL increíble Hulk",
    description: "Este es el funko de Hulk, alias Bruce Banner",
    price: 100,
    imagen: "https://deepsanddeeps.com/media/catalog/product/cache/3/image/750x750/9df78eab33525d08d6e5fb8d27136e95/d/e/deeps-and-deeps-funko-pop-avengers-age-of-ultron-el-increible-hulk--foto-completa-4776.jpg",
    stock: "true",
  },
  {
    name: "Wolverine",
    description: "Este es el funko de Wolverine, alias Logan",
    price: 100,
    imagen: "https://funkollection.es/wp-content/uploads/2019/10/img_159639_b8aa192ff58a991a1d18178ac1b44081_1.jpg",
    stock: "true",
  },
  {
    name: "Mystique",
    description: "Este es el funko de Mystique, alias Raven",
    price: 500,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQbjjleXM8YH2mcVYkY5lB_NuSCUB9yZpzvLA&usqp=CAU",
    stock: "true",
  },
  {
    name: "La Roca",
    description: "Este es el funko de La Roca",
    price: 500,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRAVZrXeMzx71HvELEyL9IyVrt_kLZnZjGLJA&usqp=CAU",
    stock: "true",
  },
  {
    name: "Mujer Invisible",
    description: "Este es el funko de Mujer Invisible",
    price: 500,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQPj9Fovd3ueQ44hVdQ-D8_hglvW11RhoxQqA&usqp=CAU",
    stock: "true",
  },
  {
    name: "Superman",
    description: "Este es el funko de Superman",
    price: 500,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRyePZg3n0dHjFUsCjS60nZUQ7TwF0nGbnIdA&usqp=CAU",
    stock: "true",
  },
  {
    name: "Batman con kiryptoarmadura",
    description: "Este es el funko de Batman con el traje de kryptonita de Batman vs Superman",
    price: 500,
    imagen: "https://www.google.com/url?sa=i&url=https%3A%2F%2Farticulo.mercadolibre.com.ar%2FMLA-627633895-funko-pop-batman-armored-legion-of-collectors-_JM&psig=AOvVaw2LnHV2AtGbX05S9pdTjeYa&ust=1604777096599000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPDXpOTS7uwCFQAAAAAdAAAAABAF",
    stock: "true",
  },
  {
    name: "Batman",
    description: "Este es el funko de Batman",
    price: 500,
    imagen: "https://cdn.discordapp.com/attachments/774280442564182059/774714514465751080/61si8R5UMML.png",
    stock: "true",
  },
  {
    name: "Wonder Woman",
    description: "Este es el funko de Batman",
    price: 500,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxH10sds60X5PTPIGqJ_Xi2sEnVy9Bdo5MKw&usqp=CAU",
    stock: "true",
  },
  {
    name: "White Canary",
    description: "Este es el funko de White Canary alias Sara Lance",
    price: 500,
    imagen: "https://hottopic.scene7.com/is/image/HotTopic/10720103_av1?$pdp_hero_large$",
    stock: "true",
  },
 
];

const categoryProducts = [
  { categoryId: 1, productId: 1 },
  { categoryId: 1, productId: 2 },
  { categoryId: 1, productId: 3 },
  { categoryId: 1, productId: 4 },
  { categoryId: 1, productId: 5 },
  { categoryId: 1, productId: 6 },
  { categoryId: 1, productId: 7 },
  { categoryId: 1, productId: 8 },
  { categoryId: 2, productId: 9 },
  { categoryId: 2, productId: 10 },
  { categoryId: 2, productId: 11 },
  { categoryId: 2, productId: 12 },
  { categoryId: 2, productId: 13 },
  { categoryId: 3, productId: 1 },
  { categoryId: 3, productId: 2 },
  { categoryId: 3, productId: 3 },
  { categoryId: 3, productId: 4 },
  { categoryId: 4, productId: 5 },
  { categoryId: 4, productId: 6 },
  { categoryId: 5, productId: 7 },
  { categoryId: 5, productId: 8 },
  { categoryId: 6, productId: 9 },
  { categoryId: 6, productId: 10 },
  { categoryId: 6, productId: 11 },
  { categoryId: 6, productId: 12 },
  { categoryId: 7, productId: 13 },
];


module.exports = {
  initialCategories,
  initialProducts,
  categoryProducts
};
